sudo: false

language: cpp

script:
    - clang++ test/test.cpp -Isrc -std=c++11 -Wno-unused-value -o test_cpp
    - clang test/test.c -Isrc -std=c99 -Wno-unused-value -o test_c
    - clang++ test/test.cpp -Isrc -std=c++11 -Wno-unused-value -DBOA_GENERIC=1 -o test_generic_cpp
    - clang test/test.c -Isrc -std=c99 -Wno-unused-value -DBOA_GENERIC=1 -o test_generic_c
    - clang++ test/test.cpp -Isrc -std=c++11 -m32 -Wno-unused-value -o test_cpp_32
    - clang test/test.c -Isrc -std=c99 -m32 -Wno-unused-value -o test_c_32
    - clang++ test/test.cpp -Isrc -std=c++11 -m32 -Wno-unused-value -DBOA_GENERIC=1 -o test_generic_cpp_32
    - clang test/test.c -Isrc -std=c99 -m32 -Wno-unused-value -DBOA_GENERIC=1 -o test_generic_c_32
    - ./test_cpp
    - ./test_c
    - ./test_generic_cpp
    - ./test_generic_c
    - ./test_cpp_32
    - ./test_c_32
    - ./test_generic_cpp_32
    - ./test_generic_c_32

